Implementation of Charge-Extended Hückel method
tblite/tblite pull request #124
Opened 2023-08-26 14:28 UTC by marcelmbn

### Full implementation of Charge-Extended Hückel (CEH) method as guess and charge model in tblite

Theoretical foundation can be obtained upon request or (shortly) in "Müller, M., Hansen, A. & Grimme, S. An atom-in-molecule adaptive polarized valence single-ζ atomic orbital basis for electronic structure calculations. _submitted to J. Chem. Phys._". The publication also gives MAEs for atomic charges and dipole moments.
CEH serves as a charge model for:
1. An atomic charge guess for the new GP3-xTB tight binding method
2. The atom-in-molecule-adaptive q-vSZP basis set as stand-alone
3. An adapted variant of q-vSZP utilized in the GP3-xTB TB method

The implementation contains (besides the CEH-specific Hamiltonian)
- An electronegativity difference-weighted coordination number
- Overlap integrals that are scaled in the diatomic frame depending on the diatomic interaction type (_sigma_, _pi_, _delta_)

CEH is by purpose not implemented as another tight-binding Hamiltonian parallel to GFN1/2 but as a guess method (along with EEQ/SAD) providing atomic charges (or a complete density matrix). The main reasons are that (i) CEH is not a tight-binding method but "only" an EHT-based model, and (ii) it provides only a density matrix but has neither an energy expression nor analytical gradients available.
The implementation uses (wherever possible and reasonable) the existing tblite infrastructure (e.g., for integrals, electronic solvers, wavefunction, ...) and includes unit tests assessing charges and dipole moments of charged molecules, probes the electric field dependency, the scaled overlap contributions and the EN-weighted coordination number.

2023-08-26 14:34 UTC, marcelmbn commented
The CEH feature (not using as a guess but as a "stand-alone" result) is accessible via the command-line call:
`tblite run --guess ceh --guessonly coord`

2023-08-26 21:19 UTC, awvwgk requested changes

2023-08-26 21:19 UTC, awvwgk commented on src/tblite/ceh/ncoord_ceh/covrad_ceh.f90
> +module tblite_data_covrad_ceh
Please make sure that the module name can be mapped tintje file name. This file should be in `src/tblite/data`

2023-08-26 21:19 UTC, awvwgk commented on src/tblite/ceh/ncoord_ceh/covrad_ceh.f90
> +   public :: get_covalent_rad
This symbol name can overlap with existing symbols, maybe rename it?

2023-08-26 21:19 UTC, awvwgk commented on src/tblite/ceh/ncoord_ceh/ncoord_ceh.f90
> +!> @dir tblite/ncoord
This direction instruction does not match with the file name

2023-08-26 21:19 UTC, awvwgk commented on src/tblite/ceh/ncoord_ceh/ncoord_ceh_standard.f90
> +!> EN-weighted and usual form.
Can those two be merged in a single interface as done for dftd4?

2023-08-26 21:19 UTC, awvwgk commented on src/tblite/ceh/ncoord_ceh/ncoord_ceh_standard.f90
> +! subroutine ncoord_derf(mol, trans, cutoff, rcov, en, cn, dcndr, dcndL)
Please remove unused code

2023-08-26 21:19 UTC, awvwgk commented on src/tblite/ceh/ncoord_ceh/type_ceh.f90
> +   type, public, abstract :: ncoord_type_ceh
Why is a separate base class needed?

2023-08-28 10:42 UTC, marcelmbn commented on src/tblite/ceh/ncoord_ceh/ncoord_ceh_standard.f90
> +! subroutine ncoord_derf(mol, trans, cutoff, rcov, en, cn, dcndr, dcndL)
Done.

2023-08-28 10:47 UTC, marcelmbn commented on src/tblite/ceh/ncoord_ceh/type_ceh.f90
> +   type, public, abstract :: ncoord_type_ceh
Refactored the setup of the coordination number such that it is included in the `tblite_ncoord` framework and not as a stand-alone directory with own classes/types.

2023-08-28 10:48 UTC, marcelmbn commented on src/tblite/ceh/ncoord_ceh/ncoord_ceh_standard.f90
> +!> EN-weighted and usual form.
See below.

2023-08-28 10:48 UTC, marcelmbn commented on src/tblite/ceh/ncoord_ceh/ncoord_ceh.f90
> +!> @dir tblite/ncoord
Obsolete now.

2023-08-28 10:48 UTC, marcelmbn commented on src/tblite/ceh/ncoord_ceh/covrad_ceh.f90
> +   public :: get_covalent_rad
Done.

2023-08-28 10:48 UTC, marcelmbn commented on src/tblite/ceh/ncoord_ceh/covrad_ceh.f90
> +module tblite_data_covrad_ceh
Done.

2023-08-28 11:56 UTC, awvwgk commented on src/tblite/wavefunction/type.f90
> +   type, public :: wavefunction_derivative_type
Why does this need its own type, can't it be incorporated with the normal wavefunction type and allocated on demand when the wavefunction is constructed?

2023-08-28 11:57 UTC, awvwgk commented on test/unit/test_integral_multipole.f90
> +      new_unittest("overlap_dipole_diat_alh3", test_overlap_dipole_diat_alh3), &
Please prefer dashes in test names

2023-08-28 12:01 UTC, awvwgk commented on app/cli.f90
> +         config%guessonly = .true.
I would prefer to have this either as a standalone (`--method ceh`) or have a separate subcommand `tblite guess --method {sad,ceh,...}`. The logic of `--guessonly` is not fitting for the run driver at the moment.

2023-08-28 15:24 UTC, marcelmbn commented on src/tblite/wavefunction/type.f90
> +   type, public :: wavefunction_derivative_type
The wavefunction derivative type was implemented as a starting point for future implementation of the CEH gradient. But since I haven't thought about if it will actually be required, I deleted it and all references for the moment and cleaned up everything. 
This (or your suggestion) can be implemented consistently in future gradient development when it is actually required.

2023-08-28 15:24 UTC, marcelmbn commented on test/unit/test_integral_multipole.f90
> +      new_unittest("overlap_dipole_diat_alh3", test_overlap_dipole_diat_alh3), &
Done.

2023-08-28 16:44 UTC, marcelmbn commented on app/cli.f90
> +         config%guessonly = .true.
(I haven't completed the change towards a new subcommand 'guess' yet, so it is to be expected that it will not work yet.)
I'll request a review when it is done.

2023-08-29 09:30 UTC, marcelmbn commented on app/cli.f90
> +         config%guessonly = .true.
Done.

2023-08-29 10:49 UTC, awvwgk commented on app/driver_run.f90
> +      ctx%verbosity = config%verbosity
The guess must not modify the verbosity of the calculation context.

2023-08-29 10:50 UTC, awvwgk commented on app/driver_run.f90
> +      call ceh_guess(ctx, calc_ceh, mol, error, wfn_ceh)
Since we pass in the calculation context here, we should check whether an error was recorded in the context and needs handling.

2023-08-29 10:51 UTC, awvwgk commented on src/tblite/ceh/CMakeLists.txt
> +  "${dir}/ceh_calculator.f90"
The prefix `ceh_` is superfluous here.

2023-08-29 12:36 UTC, awvwgk commented on app/driver_guess.f90
> -      ctx%verbosity = config%verbosity
Setting the verbosity globally via the context here and in run is okay, but having it dependent on the guess is not.

2023-08-29 12:57 UTC, marcelmbn commented on app/driver_guess.f90
> -      ctx%verbosity = config%verbosity
Okay, got it. 
In the case of `guess_main` it doesn't really matter in the end in my eyes (if it is set globally in the beginning or if the `config%verbosity` is taken). I just decided to proceed analogously to `run_main` (or how it was done before), in which `xtb_singlepoint` takes `config%verbosity` as an argument. In `guess_main`, the analog routine is the call of `ceh_guess`.

2023-08-29 13:17 UTC, marcelmbn commented
Are further steps required for the final integration into `main` of `tblite`?

2023-08-29 14:09 UTC, awvwgk requested changes
There is one thing that is currently unclear to me. When doing the Slater-Koster rotation of the integral in the diatomic frame for scaling, the transformation is done with the whole matrix rather than the contribution of the pair that is rotated. This step seems incorrect since it will destroy the integral matrix if multiple images of the atom are present. Rather the transformation needs to happen on the diatomic block level.

2023-08-29 14:10 UTC, awvwgk commented on src/tblite/integral/overlap.f90
> +         stop
This should be an error stop. Also, please don't write a separate message and than stop, rather directly write with the stop statement.

2023-08-29 14:12 UTC, awvwgk commented on src/tblite/ceh/h0.f90
> +!> @file tblite/ceh/ceh_h0.f90
```suggestion
!> @file tblite/ceh/h0.f90
```

2023-08-29 14:12 UTC, awvwgk commented on src/tblite/ceh/calculator.f90
> +!> @file tblite/ceh/ceh_calculator.f90
```suggestion
!> @file tblite/ceh/calculator.f90
```

2023-08-29 14:17 UTC, awvwgk commented on src/tblite/ceh/ceh.f90
> +               k = k + 1
Please compute those indices directly from your basis set rather than manually incrementing them from the outer loop. This avoids having unreachable error stops in this code block.

2023-08-29 14:18 UTC, awvwgk requested changes
There are some minor formatting issues where the code is currently not following the style of the rest of tblite, please check and reformat the files accordingly.

2023-08-30 11:42 UTC, marcelmbn commented
> There are some minor formatting issues where the code is currently not following the style of the rest of tblite, please check and reformat the files accordingly.

Which parts/formatting issues do you mean, for example? How can I reformat them so that they match the rest of the `tblite` style? (Do you mean some `findent`/`fprettify` settings?)

2023-08-30 12:22 UTC, marcelmbn commented on src/tblite/integral/overlap.f90
> +               endif
> There is one thing that is currently unclear to me. When doing the Slater-Koster rotation of the integral in the diatomic frame for scaling, the transformation is done with the whole matrix rather than the contribution of the pair that is rotated. This step seems incorrect since it will destroy the integral matrix if multiple images of the atom are present. Rather the transformation needs to happen on the diatomic block level.

In the above lines of code, only the pair contribution (just like you would have expected) is rotated into the diatomic frame. I.e., first, the overlap between _all_ AOs in _all_ shells between atoms `iat` and `jat` is calculated and set up. Then, this block matrix in the overlap (lines 544 to 554) is put into the transformation routine (transform forth, scale, transform back), and is added onto the second overlap matrix `overlap_scaled`. Does this answer your question?

2023-08-30 12:29 UTC, marcelmbn commented on src/tblite/integral/overlap.f90
> +         stop
Done.

2023-08-30 12:48 UTC, marcelmbn commented on src/tblite/ceh/ceh.f90
> +               k = k + 1
Done.

2023-10-02 15:09 UTC, marcelmbn commented
> There is one thing that is currently unclear to me. When doing the Slater-Koster rotation of the integral in the diatomic frame for scaling, the transformation is done with the whole matrix rather than the contribution of the pair that is rotated. This step seems incorrect since it will destroy the integral matrix if multiple images of the atom are present. Rather the transformation needs to happen on the diatomic block level.

Based on your comment and our in-person discussion, I refactored the rotation of the overlap integral elements such that it is performed on the shell level. I.e., it can used when calculating only the overlap integral elements of a single shell pair, as it is regularly done for, e.g., the setup of the GFN1/2 Hamiltonian.
Consequently, I adapted the setup of the CEH Hamiltonian to this working principle. Instead of calling a subroutine for the whole overlap matrix at the beginning of the Hamiltonian setup, the overlap integral is built step-by-step, avoiding unnecessary calculations for the symmetry-equivalent triangle.

2023-10-08 13:39 UTC, awvwgk approved these changes
Looks good to me now

2023-10-08 13:48 UTC, merged