Refactor CEH model
tblite/tblite pull request #133
Opened 2023-10-27 14:13 UTC by thfroitzheim

The CEH model implemented in #124 was refactored to follow the layout for the GFN Hamiltonians more closely. This includes: 
1. Transfer of ceh_guess into its own singlepoint.f90 file.
2. Transfer of the Hamiltonian setup and the (rewritten) get_hamiltonian function into the h0.f90 file. In this course, the new ceh_hamiltonian and ceh_calculator classes were removed and replaced by the tb_hamiltonian and xtb_calculator base classes (added data will also be required in the GP3-xTB development). 
3. Introduction of a ceh_h0spec to use the tb_hamiltonian machinery for the Hamiltonian setup. Expansion of the getter functions needed for get_hamiltonian. 
4. Consistent renaming of all variables to match the prior GFN implementation. 
5. Expansion of the CEH-specific test suite. 
The restructuring is necessary to use the already available GFN implementation for the setup of analytical charge gradients of CEH. 

The coordination number was restructured to prevent code duplication due to the many different CNs (now renamed). A new CN now only requires defining the count function and its derivative. To allow directed CN functions (i.e. erf_en, added to one partner and subtracted from the other) a directed_factor is included (I am open to better ideas). In this course, the testing was expanded to cover all possible CN implementations. 

Lastly, the derivatives of the diatomic frame scaled overlap was implemented.

2024-01-09 13:17 UTC, awvwgk commented on src/tblite/ceh/singlepoint.f90
> +   use mctc_io, only: structure_type
The comments in the import part do not add much explanation, please consider removing them, e.g. the comment `! Wavefunction` should be unnecessary for a module called `use tblite_wavefunction`. A more useful way of commenting is to describe why or how the statement or declaration is used, e.g. `use tblite_basis_type, only : get_cutoff  ! Realspace cutoff for integral calculation`.

2024-01-09 13:23 UTC, awvwgk requested changes
Thanks for taking the effort of merging the CEH hamiltonian with the xTB one, this is a quite positive change. I left a few comments on issues and bugs which I could spot while skimming through the PR.

2024-01-09 13:23 UTC, awvwgk commented on src/tblite/ceh/singlepoint.f90
> +      logical :: grad = .false.
This variable is implicitly saved, this is a bug.

2024-01-09 13:23 UTC, awvwgk commented on src/tblite/ceh/singlepoint.f90
> +      real(wp) :: nel = 0.0_wp, cutoff
Also, this variable is implicitly saved, this is generally not the wanted behavior.

2024-01-09 13:23 UTC, awvwgk commented on src/tblite/ceh/singlepoint.f90
> +      endif
Is this printout necessary here or can it be implemented on a higher level, e.g. in the guess or main driver?

2024-01-09 13:23 UTC, awvwgk commented on src/tblite/ceh/singlepoint.f90
> +   end subroutine header
tblite is by design free of headers.

2024-01-09 13:23 UTC, awvwgk commented on src/tblite/ncoord/erf.f90
> +
Please check whether the extra empty lines are necessary here.

2024-01-09 13:23 UTC, awvwgk commented on src/tblite/ncoord/exp.f90
> +   !use tblite_cutoff, only : get_lattice_points
Please removed commented out code.

2024-01-26 17:13 UTC, thfroitzheim commented on src/tblite/ceh/singlepoint.f90
> +      logical :: grad = .false.
That is good to know. I removed all cases, where it happend

2024-01-26 17:15 UTC, thfroitzheim commented on src/tblite/ceh/singlepoint.f90
> +      endif
No that is not needed. I remove it.

2024-01-26 17:35 UTC, thfroitzheim commented
I fixed all of the formatting issues you pointed out and removed unnecessary output and the implicitly saved variable definitions. In this course, I updated also the naming of the tests as now many versions of ncoord are tested, which led to a small merge conflict (I think I resolved it correctly).

It took a bit longer because there was already the first update for the CEH parameters. I updated all parameters and moved the radii and EN values into the ceh.f90 file, as they are also fitted. Otherwise, there was no major change to the code.

2024-01-26 17:45 UTC, awvwgk commented on app/cli.f90
> +      case("--etemp_guess")
Let's use dashes rather than underscores.

2024-01-26 17:47 UTC, awvwgk commented on src/tblite/ceh/h0.f90
> +      if (present(cn) .and. present(cn_en)) then
Can this be
```suggestion
      if (.not.present(cn) .or. .not.present(cn_en)) return
```
instead to reduce the level of indentation. Should also make the code structure somewhat clearer.

2024-01-26 17:51 UTC, awvwgk commented on src/tblite/ceh/singlepoint.f90
> +      !> coordination number related arrays
Please don't use docstring markers for non-docstring comments. These comments are prone to end up in the wrong place when extracted by ford or doxygen. Only dummy variables or procedures should have comments with the docstring marker `>`.

2024-01-26 17:52 UTC, awvwgk commented on src/tblite/ncoord/exp.f90
> +!> Same as in dftd3 reimplemented
Does this need a dot or comma at the end of the previous sentence?

2024-01-26 17:54 UTC, awvwgk approved these changes
Only some minor comments, now it looks like in a good shape to get merged.

2024-01-26 22:24 UTC, thfroitzheim commented on src/tblite/ceh/singlepoint.f90
> +      !> coordination number related arrays
I have found a few more and removed them.

2024-01-26 22:25 UTC, thfroitzheim commented on src/tblite/ceh/h0.f90
> +      if (present(cn) .and. present(cn_en)) then
That is a better way.

2024-01-26 22:26 UTC, thfroitzheim commented
Great. I have fixed the few points you mentioned and also updated the help page for the guess.

2024-01-27 08:40 UTC, awvwgk commented
Can you please also make sure the entries in man/ are consistent with the help output?

2024-01-27 10:41 UTC, thfroitzheim commented
I have added a new page to man for the guess and the guess temperature to the page for run.

2024-01-28 10:59 UTC, awvwgk approved these changes
Looks good to me now

2024-01-31 16:57 UTC, thfroitzheim commented
I think that you will have to merge the PR as I am not a maintainer (there is no hurry, but you don't have to wait for me).

2024-01-31 18:42 UTC, merged