Full ALPB/GBSA with empirical parameters
tblite/tblite pull request #142
Opened 2023-12-05 16:39 UTC by haneug

Initial and crude implementation of the 'full' ALPB and GBSA solvation models as in xtb. 

- Until now only tested for water in water and water in acetonitrile. Gradients looked decent but total energies are missing Gshift. Should Gshift be added here or in a separate pull request? 
- Should the original 'non-empirical' alpb and gbsa be discarded?
- No support for API yet. I guess this should be a separate pull request?
 
Looking forward for your suggestions how to improve this!

2023-12-06 07:56 UTC, awvwgk commented on app/driver_run.f90
> +   type(run_config), intent(inout) :: config
This should stay intent in

2023-12-06 09:50 UTC, haneug commented on app/driver_run.f90
> +   type(run_config), intent(inout) :: config
Definitely, I want to set the parameters in new_solvation because there I have mol available. My quick (and dirty?) solution is to use a scratch_input in new_solvation so that I do not have to modify config%solvation%alpb.

2024-02-15 14:57 UTC, haneug commented
Differences for GFN1-xTB do not occur for molecules with only one species e.g., H2, F2, and O3, but for molecules with multiple species e.g., HF, H2O, and CO2.

2024-08-16 20:33 UTC, pprcht commented
Hi all,

To put this issue a bit forward, I committed some changes to @haneug's branch. I think this is an important PR, so I'm happy to further work on it.

Here's what I did:
- Updated the branch to the current main branch stage.
- Updated solvent strings. Some solvents like `dmf`, `thf`, `cs2` and a few others were not available under these names, but could be selected under their full name. `tblite` now knows the alias as well. `acetone` was missing entirely, I added the entry with parameters from MNSOL.
- The solvents `furane`, `benzaldehyde`, `dioxane`, `phenol` and `woctanol` were not available in `tblite` *nor* in MNSOL. I added their entries to the `get_solvent_data` constructor, but they only contain the dielectric constant and refractory indices.
- The discrepancy between GFN1-xTB energies stemmed from a CM5 charge implementation in `xtb` that was missing in `tblite`. Not anymore.
- Finally, I tested all GFN1/GFN2 GBSA/ALPB combinations with all available solvents. The test molecule was caffeine:
```
$coord
         -6.134194835085         -2.050583457383          0.041501488892     c
         -4.257989774446         -0.077573907965         -0.001827990178     n
         -4.712442263975          2.470621717876         -0.013111881308     c
         -2.592957527478          3.781873878383         -0.016386752339     n
         -0.735810404277          1.998874697504         -0.012516600988     c
         -1.696825680417         -0.388511985183         -0.013341342571     c
         -0.165536422836         -2.593558889366         -0.012308491761     c
         -1.052950170836         -4.736438814102         -0.016475781913     o
          2.417331343252         -2.043834570361         -0.004348903618     n
          4.182092079482         -4.138750561195          0.008357048520     c
          3.486490066997          0.397636251409          0.000102411769     c
          5.802113920722          0.690657762313          0.005286648234     o
          1.822761570451          2.443307017589         -0.000190631983     n
          2.776162986238          5.014434390170          0.020533754716     c
         -8.020562503708         -1.210549395752         -0.004021712955     h
         -5.897943375362         -3.139351862292          1.780647162725     h
         -5.867941387821         -3.252537075648         -1.616202723931     h
         -6.598840021510          3.263573033853         -0.013105328556     h
          3.236734851046         -5.974575385829          0.004320331970     h
          5.372500093097         -4.001905151256          1.695285118496     h
          5.396766837421         -4.005607709880         -1.661375665537     h
          4.840892905022          5.070245799787          0.070744083415     h
          2.052500009863          5.991405353355          1.694401414324     h
          2.131182261180          5.989581702181         -1.685866648900     h
$end
```
Here are the summarized results:
[gfn2-gbsa-results.txt](https://github.com/user-attachments/files/16641356/gfn2-gbsa-results.txt)
[gfn2-alpb-results.txt](https://github.com/user-attachments/files/16641357/gfn2-alpb-results.txt)
[gfn1-gbsa-results.txt](https://github.com/user-attachments/files/16641358/gfn1-gbsa-results.txt)
[gfn1-alpb-results.txt](https://github.com/user-attachments/files/16641360/gfn1-alpb-results.txt)

As Hagen mentioned in the beginning, the deviation in total energy w.r.t. the `xtb` implementation was on the order of ~10<sup>-8</sup> Eh, and it still is, now for all solvents and both Hamiltonians. The gradients match pretty well, too.

### TODO
As I said above, I'm happy to continue working on this and there may be still some things to do. It would be great if you advise me on how/what you would like for the implementation.
- add some tests
- More cleanup? E.g. should setting this implementation be kept as `--alpb-xtb`/`--gbsa-xtb` or would you prefer it to be just `--alpb`/`--gbsa`? The latter may be preferable to avoid confusion...

2024-08-17 20:25 UTC, pprcht commented
Added some tests and fixed some of the logic of CM5 charge allocation

2024-11-05 14:40 UTC, pitsteinbach commented
I added the python and C-API, for the changes done by the other guys and added some tests to go along.
I had to add a string to the calculator containing the method to retrieve this information in the container API, sop that the right parameters can be chosen.

2024-11-06 13:22 UTC, thfroitzheim commented
This should now be ready for review. It is tested for all solvents against xtb. Most remaining misses in code coverage are in the CLI for which there are additional test.

2024-11-09 14:49 UTC, awvwgk requested changes

2024-11-09 14:49 UTC, awvwgk commented on include/tblite/container.h
> +#define tblite_new_alpb_solvation(...) vrg(tblite_new_alpb_solvation, __VA_ARGS__)
Why is it necessary to have variadic functions here. Let's define two separate and clean APIs and combine them with a type generic macro instead.

Keep in mind eventually we need to expose the ABI to Python and any macro trick we are using in C is not possible to export there.

2024-11-09 14:49 UTC, awvwgk commented on include/tblite/container.h
> +char * std_refstr = "gsolv";
Instead of using a global variable here we can define an enumerator for the reference state instead. If passed as int* a NULL would show absence of the optional argument. In Python we can add a wrapper to convert strings to enums to make it more user-friendly.

2024-11-11 13:25 UTC, pitsteinbach commented on include/tblite/container.h
> +#define tblite_new_alpb_solvation(...) vrg(tblite_new_alpb_solvation, __VA_ARGS__)
Well I wanted to keep the API for ALPB and GBSA constant and identical to that of CPCM, default values are not possible in C and from what I could find on the internet variadic functions are the way to go.
I don't see how to combine using a Generic Macro since from what I can find, Generic must have an operand which would not be possible if you call new_alpb_solvation with only 4 arguments.

I don't understand your second point, since Generic is also a macro trick or isn't it? Maybe you can point me to some further reading.

2024-11-11 13:46 UTC, pitsteinbach commented on include/tblite/container.h
> +char * std_refstr = "gsolv";
I proposed a solution using an enum and `int*` API, which impacted the general ALPB/GBSA API. I also propose a python wrapper for the enum I don't know if that is what you expected.

2024-12-04 10:05 UTC, awvwgk commented on app/tester.py
Can we move this to `test/validation` to keep the app directory clean with only the files relevant for distribution?

2024-12-04 10:07 UTC, awvwgk commented on app/cli.f90
> +            if (arg == "gsolv") then
Let's add a new option called `--solvation-state` or similar instead of making the options for the solvation model more involved.

2024-12-11 11:14 UTC, awvwgk approved these changes

2024-12-11 11:33 UTC, merged

2024-12-11 11:57 UTC, awvwgk commented
Thanks Hagen @haneug, Philipp @pprcht, Thomas @thfroitzheim and Pit @pitsteinbach for the all the hard work on this.