Fix OMP memory leak in Coloumb matrix derivatives
tblite/tblite pull request #154
Opened 2024-01-19 22:15 UTC by pprcht

Many thanks for this awesome software!

I've noticed an apparent leak of memory that occurs for a large number of energy+gradient evaluations (e.g. during long MD simulations or extensive sampling applications). 
For a handful of e+grd calls one barely notices it, but the memory consumption becomes severe over time, leading to swapping and eventually blows up the call:
![memory](https://github.com/tblite/tblite/assets/42216327/4b7b25c7-720b-4e92-b8ba-a8b6e119f108)

## How to reproduce?
The error can be easily reproduced with the `tblite` app, e.g. by simply building a loop around the `xtb_singlepoint` call. To reproduce it the gradient calculation (`--grad`) must be requested, a simple SCC without gradient does *not* show this.
Concerning technical setting: 
I've been using the latest  commit from the main branch (#152) and the build was created using
**meson 1.2.0** and **ifort 2021.9.0** with an MKL backend from the same oneAPI verison. 
The build was a static one, i.e., using `--default-library=static`, as well as Fortran link arguments `-static` and `-qopenmp`, but otherwise used the default build options.

## What was changed?
I've traced the memory consumption back to the OMP-parallel evaluation of the Coloumb matrix derivatives. My interpretation of what happens is that the implicit allocation of
```
   itrace = atrace
   didr = dadr
   didL = dadL
```
***within*** the OMP statement does not free up the respective memory correctly after execution of the subroutines `get_damat_3d` and `get_damat_0d`. This could be a problem endemic to the `ifort` build, but I'm not 100% sure about that. 
Allocating the three tensors *before* the OMP statement resolves the issue and even a few hundred thousand energy and gradient calls do not increase the memory consumption. 
![memory2](https://github.com/tblite/tblite/assets/42216327/37df82d9-3b49-4031-972a-aa10e57fa35e)

All builds and unit tests are passing, there is no other internal or external change to the behavior of the code. :+1:

2024-01-20 17:57 UTC, awvwgk requested changes
Can we move the sourced allocation in the omp region? This allocation should be done by each thread and not in a sequential region and then broadcast.

2024-01-20 18:12 UTC, pprcht commented
> Can we move the sourced allocation in the omp region? This allocation should be done by each thread and not in a sequential region and then broadcast. Maybe we can explicitly deallocate the arrays after the omp loop.

Yes, makes sense. Let me check!

2024-01-20 18:16 UTC, pprcht commented
Explicit allocation/deallocation within the OMP region does it.

2024-01-20 21:49 UTC, awvwgk commented on src/tblite/coulomb/charge/effective.f90
> +   deallocate(didL,didr,itrace)
```suggestion
   deallocate(didL, didr, itrace)
```

2024-01-20 21:49 UTC, awvwgk commented on src/tblite/coulomb/charge/effective.f90
> +   deallocate(didL,didr,itrace)
```suggestion
   deallocate(didL, didr, itrace) 
```

2024-01-20 21:50 UTC, awvwgk approved these changes

2024-01-20 21:53 UTC, awvwgk requested changes
Sourced allocation should be identical to automatic LHS allocation on assignment, can we remove the either the assignment or the allocation? The main issue of the leak seems to be the missing deallocation.

2024-01-21 00:26 UTC, pprcht commented
> Sourced allocation should be identical to automatic LHS allocation on assignment, can we remove the either the assignment or the allocation? The main issue of the leak seems to be the missing deallocation.

It is. I left the sourced allocation and removed the LHS assignment. This way it is slightly more obvious where the corresponding deallocation comes from.

2024-01-21 11:23 UTC, awvwgk approved these changes

2024-01-21 11:23 UTC, merged