Updated spGFN2 spin constants
tblite/tblite pull request #155
Opened 2024-01-26 17:11 UTC by benbaed

The constants were now computed using a more sophisticated script (minor changes in the last digits might occur)
The rare gases were fixed (now actually PBE is used, before it was HF by accident)
Cr, Cu, Y, Zr, Pd, Pt & Au were changed in the electronic configuration to avoid "jumps", the d-related constants changed
B, Cl, Ir & Bi were adjusted in a minor way.

2024-01-26 17:56 UTC, awvwgk requested changes
Please check the unit tests that are now failing.

2024-07-30 15:23 UTC, awvwgk commented
Thank you for this contribution, I see that you pushed another commit after my review, however the main point of the review comments remains unaddressed for me. Could you clarify why more spin constants than the ones mentioned in the PR are changed here?

2024-12-16 15:36 UTC, awvwgk commented
Looks like the C-API and spin related unit tests are failing:

````
Summary of Failures:

19/82 tblite:unit / spin                      FAIL            0.18s   exit status 1
82/82 tblite:api / C-API                      FAIL            1.20s   exit status 1
````

2024-12-16 22:02 UTC, thfroitzheim commented
I updated the test and restructured them a bit more generally for possible later extensions. 

I also fixed the CI and wheels again. With the switch to ubuntu-latest being 24.04 Github seems to have removed packages (https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/). Here it mostly impacted Lapack.

2025-02-13 15:38 UTC, awvwgk approved these changes

2025-02-13 15:39 UTC, merged