Raise error for too heavy elements
tblite/tblite pull request #188
Opened 2024-07-30 12:47 UTC by marcelmbn

## Adding error raise for too heavy elements

In the existing implementation, using actinoids (or in general elements `Z>=87`) leads to memory errors or stopped execution of the program. To prevent this (not intended behavior), each calculator checks for `any(mol%num > max_elem)`.

- changed tests
- changed calculator calls
- added error raise for each calculator (`ceh`, `gfn2`, `gfn1`, `ipea1`)

2024-07-30 15:16 UTC, awvwgk requested changes

2024-07-30 15:16 UTC, awvwgk commented on src/tblite/api/calculator.f90
> +   if (allocated(error)) then
This error should be pushed to the context object, such that API users can get a clear understanding of the reason for the error

2024-07-30 15:16 UTC, awvwgk commented on src/tblite/ceh/ceh.f90
> +         call fatal_error(error, "No support for elements with Z >" // max_elem_str // ".")
We have a format function to avoid using internal writes in tblite

2024-07-30 15:16 UTC, awvwgk commented on test/unit/test_ceh.f90
> +      call new_ceh_calculator(calc, mol, error)
Please also handle the errors here and subsequent cases

2024-07-30 17:24 UTC, marcelmbn commented on test/unit/test_ceh.f90
> +      call new_ceh_calculator(calc, mol, error)
Do you mean something like this:
```
      call new_ceh_calculator(calc, mol, error)
      if (allocated(error)) return
```

The error itself is propagated to the test suite itself automatically, if I understand the `tests` correctly.

2024-07-30 18:24 UTC, awvwgk requested changes

2024-07-30 18:24 UTC, awvwgk commented on src/tblite/ceh/ceh.f90
> +         call fatal_error(error, "No support for elements with Z >" // format_string(max_elem, '(i3)') // ".")
To avoid leading whitespace 
```suggestion
         call fatal_error(error, "No support for elements with Z >" // format_string(max_elem, '(i0)') // ".")
```

2024-07-30 18:24 UTC, awvwgk commented on src/tblite/api/calculator.f90
> +   if (allocated(error)) then
Same for the other API calls as well ;)

2024-07-30 18:24 UTC, awvwgk commented on src/tblite/xtb/gfn1.f90
> +   !> Check if all atoms of mol%nat are supported (Z <= 86)
Don't use docstring in the procedure body, they lead to artifacts for the generated docs
```suggestion
   ! Check if all atoms of mol%nat are supported (Z <= 86)
```

2024-07-30 22:02 UTC, marcelmbn commented on src/tblite/xtb/gfn1.f90
> +   !> Check if all atoms of mol%nat are supported (Z <= 86)
Okay, good to know!

2024-07-30 22:45 UTC, marcelmbn commented on src/tblite/api/calculator.f90
> +   if (allocated(error)) then
Sure, just noticed that I have pushed it only for the example one.

2024-07-31 06:56 UTC, awvwgk reviewed
Errors need to be handled as soon as possible, there is no guarantee that the next calls will succeed if the previous fails, especially if they depend on the state of the calculator

2024-07-31 06:56 UTC, awvwgk commented on app/driver_run.f90
> +      call new_ceh_calculator(calc_ceh, mol, error)
```suggestion
      call new_ceh_calculator(calc_ceh, mol, error)
      if (allocated(error)) return
```

2024-07-31 06:56 UTC, awvwgk commented on app/driver_run.f90
> +   if (allocated(error)) return
```suggestion
```

2024-07-31 07:03 UTC, awvwgk commented on app/driver_guess.f90
> +         call new_ceh_calculator(calc_ceh, mol, error)
```suggestion
         call new_ceh_calculator(calc_ceh, mol, error)
         if (allocated(error)) return
```

2024-07-31 07:04 UTC, awvwgk approved these changes
Thanks for sharing. Looks good to me now

2024-07-31 07:16 UTC, merged