Gradient of the electrostatics potential
tblite/tblite pull request #193
Opened 2024-08-01 09:31 UTC by thfroitzheim

I added position and lattice vector gradients of the potential for second-order and onsite third-order electrostatics. This is the first step towards gradients of the CEH charges, as they require the derivative of the Hamiltonian for the coupled-perturbed equations (a later PR). Changes include: 
- add get_potential_gradient to the potential_type and all derived types. 
- add charge derivatives to the wavefunction type. 
- add derivatives to the effective charges for the CEH electrostatics
- add explicit testing for the onsite thirdorder (also a useful starting point in the future for full thirdorder ES).

2024-10-09 17:09 UTC, awvwgk requested changes

2024-10-09 17:09 UTC, awvwgk commented on src/tblite/ceh/ceh.f90
> +      if (present(dqatdr) .and. present(dqatdL)) then
This branch does not check for the presence of dcn_endr and access them even if they are not provided

2024-10-09 17:09 UTC, awvwgk commented on src/tblite/ceh/ceh.f90
> +      real(wp), intent(in), optional :: dcn_endr(:, :, :), dcn_endL(:, :, :)
Please split those over multiple lines

2024-10-09 17:09 UTC, awvwgk commented on src/tblite/coulomb/charge/type.f90
> +            call symv(ptr%amat, wfn%dqatdr(ic, iat, :, 1), pot%dvatdr(ic, iat, :, 1), beta=1.0_wp)
Please explicitly copy those slices into a temporary array to avoid that the compiler creates them in an inefficient way

2024-10-09 17:09 UTC, awvwgk commented on src/tblite/coulomb/charge/type.f90
> +            call symv(ptr%amat, wfn%dqatdL(ic, jc, :, 1), pot%dvatdL(ic, jc, :, 1), beta=1.0_wp)
Same here, please don't rely on the compiler to create temporary contiguous arrays for you

2024-10-09 17:09 UTC, awvwgk commented on src/tblite/coulomb/multipole.f90
> +   type(coulomb_cache), pointer :: ptr
Unused

2024-10-09 17:09 UTC, awvwgk commented on src/tblite/coulomb/thirdorder.f90
> +   if (.not. self%shell_resolved) then
What happens in the shell resolved case? Can we at least raise an error if this is not supported rather than falling through silently

2024-10-09 20:29 UTC, thfroitzheim commented on src/tblite/coulomb/thirdorder.f90
> +   if (.not. self%shell_resolved) then
You are right that it doesn't make much sense to break the support for both shell- and atom-resolved ES over this small addition. I added the shell-resolved case and tested it in the CEH context with atomic charges distributed over the shells.

2024-10-10 07:05 UTC, awvwgk approved these changes
Looks good to me

2024-10-10 07:07 UTC, merged