Pin dependency versions also in meson.build
tblite/tblite pull request #215
Opened 2024-11-08 22:04 UTC by thfroitzheim

I also pinned the dependency versions in the meson.build files. We might want to use a ">=" but to allow for a xtb build where all dependencies are consistent, this seems to require specification here to.

2024-11-08 22:48 UTC, awvwgk requested changes
Please retain the version ranges. If there is no breaking API change from the dependencies are a new API that requires a certain lower bound we should leave the flexibility to discover all compatible versions of a dependency.

2024-11-09 16:47 UTC, awvwgk requested changes

2024-11-09 16:47 UTC, awvwgk commented on config/meson.build
> +  version: '>=3.4.0',
This needs an upper bound of v4

2024-11-09 17:06 UTC, marvinfriede commented on config/meson.build
> +  version: '>=3.4.0 <4.0.0',
```suggestion
  version: ['>=3.4.0', '<4'],
```

2024-11-10 09:54 UTC, awvwgk approved these changes

2024-11-10 20:07 UTC, merged